apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdac-seed
  labels:
    app: hdac-seed
spec:
  selector:
    matchLabels:
      app: hdac-seed
  replicas: 1
  template:
    metadata:
      labels:
        app: hdac-seed
    spec:
      containers:
        - name: hdac-seed
          image: buryeye7/hdac-seed:latest
          env:
            - name: COUCHDB
              value: couchdb-app-svc
            - name: TARGET 
              value: {TARGET}
            - name: WALLET_CNT
              value: {WALLET_CNT}
          command: ["./scripts/start-seed.sh"]
          ports:
            - name: rpc
              containerPort: 26657
              protocol: TCP
            - name: network
              containerPort: 26656
              protocol: TCP
            - name: clif
              containerPort: 1317
              protocol: TCP
            - name: prometheus
              containerPort: 26660
              protocol: TCP
      nodeName: {NODE_NAME} 

---
apiVersion: v1
kind: Service
metadata:
  name: hdac-seed
spec:
  type: LoadBalancer
  selector:
    app: hdac-seed
  ports:
    - name: clif-rest
      protocol: TCP
      port: 1317
      targetPort: 1317
    - name: profiling
      protocol: TCP
      port: 6060
      targetPort: 6060

