apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdac-node4
spec:
  selector:
    matchLabels:
      run: hdac-node4
  replicas: 1
  template:
    metadata:
      labels:
        run: hdac-node4
    spec:
      containers:
        - name: hdac-node4
          image: buryeye7/hdac-node:latest
          command: ["./scripts/start-node.sh"]
          ports:
            - name: rpc
              containerPort: 26657
              protocol: TCP
            - name: network
              containerPort: 26656
              protocol: TCP
            - name: clif
              containerPort: 1317
              protocol: TCP
            - name: prometheus
              containerPort: 26660
              protocol: TCP
