apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdac-node{NO}
spec:
  selector:
    matchLabels:
      run: hdac-node{NO}
  replicas: 1
  template:
    metadata:
      labels:
        run: hdac-node{NO}
    spec:
      containers:
        - name: hdac-node{NO}
          image: buryeye7/hdac-node:latest
          command: ["./scripts/start-node.sh"]
          ports:
            - name: rpc
              containerPort: 26657
              protocol: TCP
            - name: network
              containerPort: 26656
              protocol: TCP
            - name: clif
              containerPort: 1317
              protocol: TCP
            - name: prometheus
              containerPort: 26660
              protocol: TCP
      nodeName: {NODE_NAME}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hdac-node-app
  name: ndac-node-app-svc
spec:
  ports:
  - nodePort: 31317
    port: 1317
    protocol: TCP
    targetPort: 1317
  selector:
    app: hdac-node-app
  type: NodePort
